[tool.poetry]
name = "warnet-bot"
version = "1.5.0"
description = "A bot for Warga Nusantara Teyvat (WARNET) discord server"
authors = ["Iqrar Agalosi Nureyza <misteriqrar@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/Iqrar99/WarnetBot"

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^0.21.0"
discord-py-pagination = "^0.0.5"
asyncpg = "^0.27.0"
discord-py = "^2.1.1"
pytz = "^2022.7.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
black = "^23.1.0"
taskipy = "^1.10.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
start = "python -m bot"